// Generated by CoffeeScript 2.7.0
(function() {
  /*
  composer
  @usage:
      grunt composer:args...
  */
  module.exports = function(grunt) {
    if (grunt.config('composer')) {
      return grunt.registerMultiTask('composer', 'Wrapper around Composer commands', function(command, ...flags) {
        return module.exports.handleTask(this, command, flags);
      });
    } else {
      return grunt.registerTask('composer', 'Wrapper around Composer commands', function(command, ...flags) {
        return module.exports.handleTask(this, command, flags);
      });
    }
  };

  module.exports.handleTask = function(self, command, flags) {
    var commandBuilder, commandToRun, cur_cwd, cwd, result;
    require('shelljs/global');
    commandBuilder = require('./lib/commandBuilder');
    commandToRun = commandBuilder.withConfig(self.options()).withFlags(flags).withCommand(command).build();
    cur_cwd = process.cwd();
    cwd = self.options().cwd;
    if (cwd) {
      cd(cwd);
    }
    result = exec(commandToRun).code === 0;
    if (cwd) {
      cd(cur_cwd);
    }
    return result;
  };

}).call(this);
